tls:
  certificates:
    - certFile: /etc/traefik/cert/fullchain.pem
      keyFile: /etc/traefik/cert/privkey.pem
      stores:
        - default
  #    - certFile: /etc/traefik/cert/selfsigned.pem
  #      keyFile: /etc/traefik/cert/selfkey.pem
  #      stores:
  #        - default
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/cert/fullchain.pem
        keyFile: /etc/traefik/cert/privkey.pem
  options:
    default:
      sniStrict: true
